language: crystal

before_install:
- scripts/install_libsass_ci.sh

after_success:
- scripts/autodeploy-docs.sh

env:
  global:
    GIT_COMMITTER_NAME: travis-ci
    GIT_COMMITTER_EMAIL: travis@travis-ci.org
