language: crystal

env:
  global:
    GIT_COMMITTER_NAME: travis-ci
    GIT_COMMITTER_EMAIL: travis@travis-ci.org
    LIBSASS_VERSION: 3.5.0.beta.3
    LOCAL_LD_PATH: ${TRAVIS_BUILD_DIR}/dynlib

cache:
  directories:
  - ${LOCAL_LD_PATH}

script: make spec

after_success:
- scripts/generate-docs.sh
- curl https://raw.githubusercontent.com/straight-shoota/autodeploy-docs/master/autodeploy-docs.sh | bash
